In [ ]:
'''
Name   : Rupesh Garsondiya
github : @Rupeshgarsondiya
Topic  : NN module and torch.optim in torch (Deep-Learning with PyTorch)
'''

'\nName   : Rupesh Garsondiya\ngithub : @Rupeshgarsondiya\nTopic  : NN module and torch.optim in torch (Deep-Learning with PyTorch)\n'

# NN module of PyTorch

- Core torch library it's  provide wide array of classes and functions designed to help devloper build neural network efficiently and effectively

**Key components of torch.nn :**

1. Modules (Layers)

   Examples: nn.Linear, nn.Conv2d, nn.LSTM (recurrent layer)

2. Activation Functions
   
   Examples: nn.Sigmoid, nn.ReLU, nn.Tanh

3. Loss Functions

   Examples: nn.CrossEntropyLoss, nn.MSELoss

4. Container Modules

   Example: nn.Sequential (A sequential container to stack layers in order)

5. Regularization and Dropout
   
   Examples: nn.BatchNorm2d, nn.Dropout



**This is totally practical 😀, so let's understand it with code.**

In [4]:
# create model class
import torch
import torch.nn as nn

In [17]:
# Load sci-kit learn in build dataset
from sklearn.datasets import load_breast_cancer

X,y = load_breast_cancer(return_X_y=True)

print("X shape : ",X.shape)
print("y shape : ",y.shape)


X = torch.FloatTensor(X)
y = torch.FloatTensor(y)


print(" Type X : ",type(X))
print(" Type y : ",type(y))

X shape :  (569, 30)
y shape :  (569,)
 Type X :  <class 'torch.Tensor'>
 Type y :  <class 'torch.Tensor'>


In [35]:
class Model(nn.Module) :

    def __init__(self,num_feature) :

        super().__init__() # call parent class constructor
        self.layer1 = nn.Linear(num_feature,2)  # define layer1
        self.layer2 = nn.Linear(2,1)   # define layer2
        self.sigmoid = nn.Sigmoid()    # define activation function

        self.loss_function = nn.BCELoss() # define loss


    def forward(self,x) :
        y_pred = self.layer1(x)
        y_pred = self.sigmoid(y_pred)
        y_pred = self.layer2(y_pred)
        y_pred = self.sigmoid(y_pred)
        return y_pred

model = Model(X.shape[1])

optimizer = torch.optim.Adam(model.parameters(),lr=0.01)  #model.parameter is an iterator to give all the trainable parameter

for i in range(1000) :
    y_hat = model(X)
    loss = model.loss_function(y_hat,y.view(-1,1)) # view function work same as the calculate the loss
    optimizer.zero_grad()  # gradient is zero
    loss.backward()
    optimizer.step()

In [20]:
print("----Weight and bais Layer1-----")
print(model.layer1.weight)
print(model.layer1.bias)
print("----Weight and bais Layer2-----")
print(model.layer2.weight)
print(model.layer2.bias)

----Weight and bais Layer1-----
Parameter containing:
tensor([[ 0.1281,  0.1376,  0.1337,  0.0605, -0.1788,  0.0671, -0.0352,  0.0374,
         -0.0349, -0.0321, -0.0048, -0.0761, -0.1150, -0.1315, -0.0944,  0.1294,
          0.0831,  0.0467,  0.1393,  0.1156,  0.0414, -0.0368,  0.1283, -0.1048,
         -0.0197,  0.1269, -0.0006,  0.0256, -0.0170,  0.0506],
        [ 0.1451, -0.1454,  0.1500, -0.0258,  0.0342,  0.1516, -0.1669,  0.0075,
          0.0630, -0.1511, -0.0636, -0.1259, -0.1595, -0.0735, -0.1038,  0.0446,
          0.0367, -0.0946,  0.0818, -0.0407,  0.0954, -0.0049,  0.0677,  0.0415,
          0.0742, -0.1383, -0.1736,  0.1353,  0.1600, -0.1077]],
       requires_grad=True)
Parameter containing:
tensor([-0.0618, -0.0766], requires_grad=True)
----Weight and bais Layer2-----
Parameter containing:
tensor([[ 0.6186, -0.5790]], requires_grad=True)
Parameter containing:
tensor([0.6683], requires_grad=True)


In [21]:
from torchinfo import summary
summary(model,input_size=X.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [569, 1]                  --
├─Linear: 1-1                            [569, 2]                  62
├─Sigmoid: 1-2                           [569, 2]                  --
├─Linear: 1-3                            [569, 1]                  3
├─Sigmoid: 1-4                           [569, 1]                  --
Total params: 65
Trainable params: 65
Non-trainable params: 0
Total mult-adds (M): 0.04
Input size (MB): 0.07
Forward/backward pass size (MB): 0.01
Params size (MB): 0.00
Estimated Total Size (MB): 0.08

# Complex neural Net (With hidden layer)

In [22]:
# Create more complex neural nertwork with moore hidden layer

class Model1(nn.Module) :

    def __init__(self,num_feature) :

        super().__init__() # call parent class constructor
        self.layer1 = nn.Linear(num_feature,25)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(25,12)
        self.layer3 = nn.Linear(12,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,x) :
        y_pred = self.layer1(x)
        y_pred = self.relu(y_pred)
        y_pred = self.layer2(y_pred)
        y_pred = self.relu(y_pred)
        y_pred = self.layer3(y_pred)
        y_pred = self.sigmoid(y_pred)
        return y_pred

model1 = Model1(X.shape[1])
y_hat1 = model1(X)
print(summary(model1,input_size=X.shape))


# Here 1 problem this is samll neural net or less hidden layer if we have more hidden layer and complex neural net then this is tedius process to to define layer and activation function
# Here we use sequential

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [569, 1]                  --
├─Linear: 1-1                            [569, 25]                 775
├─ReLU: 1-2                              [569, 25]                 --
├─Linear: 1-3                            [569, 12]                 312
├─ReLU: 1-4                              [569, 12]                 --
├─Linear: 1-5                            [569, 1]                  13
├─Sigmoid: 1-6                           [569, 1]                  --
Total params: 1,100
Trainable params: 1,100
Non-trainable params: 0
Total mult-adds (M): 0.63
Input size (MB): 0.07
Forward/backward pass size (MB): 0.17
Params size (MB): 0.00
Estimated Total Size (MB): 0.25


# Define neural net using container



In [47]:
class Model1(nn.Module) :
    '''
     Explenation of nn.Sequential  : The nn.Sequential module in PyTorch allows you to stack layers in a predefined order without explicitly writing each layer's forward pass.
     This makes it easier to build simple feedforward networks.
    '''

    def __init__(self,num_feature) :

        super().__init__() # call parent class constructor
        self.network = nn.Sequential(
            nn.Linear(num_feature,25),
            nn.ReLU(),
            nn.Linear(25,12),
            nn.ReLU(),
            nn.Linear(12,1),
            nn.Sigmoid()
        )
        self.loss_function1 = nn.BCELoss()
    def forward(self,x) :
        y_pred = self.network(x)
        return y_pred                       #Here, we don't need to manually define each layer. Once we create a Sequential module, it automatically defines the neural network structure.

model1 = Model1(X.shape[1])
optimizer1 = torch.optim.Adam(model1.parameters(),lr=0.01)  #model.parameter is an iterator to give all the trainable parameter
for i in range(1000) :
    y_hat = model1(X)
    loss1 = model1.loss_function1(y_hat,y.view(-1,1)) # view function work same as the calculate the loss
    optimizer1.zero_grad()  # gradient is zero
    loss1.backward()
    optimizer1.step()
    print("Epochs : ",i," ",'Loss : ',loss1.item())


Epochs :  0   Loss :  0.8486459255218506
Epochs :  1   Loss :  27.099905014038086
Epochs :  2   Loss :  25.342174530029297
Epochs :  3   Loss :  15.061285018920898
Epochs :  4   Loss :  1.6316688060760498
Epochs :  5   Loss :  2.2016522884368896
Epochs :  6   Loss :  3.1514077186584473
Epochs :  7   Loss :  2.7868692874908447
Epochs :  8   Loss :  2.0729081630706787
Epochs :  9   Loss :  1.2583277225494385
Epochs :  10   Loss :  0.7341236472129822
Epochs :  11   Loss :  0.7197425365447998
Epochs :  12   Loss :  1.0198312997817993
Epochs :  13   Loss :  1.1203569173812866
Epochs :  14   Loss :  0.953383207321167
Epochs :  15   Loss :  0.7325643301010132
Epochs :  16   Loss :  0.5918753147125244
Epochs :  17   Loss :  0.5373269319534302
Epochs :  18   Loss :  0.4826829731464386
Epochs :  19   Loss :  0.4439253807067871
Epochs :  20   Loss :  0.4640454649925232
Epochs :  21   Loss :  0.4695962965488434
Epochs :  22   Loss :  0.4350935220718384
Epochs :  23   Loss :  0.4280313551425934
Epo